<script type="text/javascript" src="js/jquery-cycle.js"></script>



<p class="title">Accueil</p>


<?php
	$db = new DatabaseManager;

	$db->Connect($db_config);


	$query = 'SELECT news_id FROM News ORDER BY news_id DESC LIMIT 5';
	$db->ApplyQuery($query);

	$data = $db->GetNext();
	$last = $data['news_id'];
	$first = $last;

	while($data = $db->GetNext())
	{
	  $first = $data['news_id'];
	}
?>

<script type="text/javascript">
var first_news = <?php echo $first; ?>; // Generated by PHP
var last_news = <?php echo $last; ?>; // Generated by PHP
var curr_news = last_news + 1;
var initNews = 0;

function displayNews() {
	$('#news_link').attr("href", "index.php?page=news&nb_news=" + curr_news);

	for(i = first_news; i <= last_news; i++) {
		$('#news_' + i).css("display", "none");
	}

	$('#news_' + curr_news).css("display", "block");
}

function nextNews() {
	curr_news--;

	if(curr_news < first_news) {
		curr_news = last_news;
	}


	displayNews();
}

function prevNews() {
	curr_news++;

	if(curr_news > last_news) {
		curr_news = first_news;
	}

	displayNews();
}

function onChangeNext() {
	if(initNews == 0) {
		nextNews();
		initNews = 1;
	} 
	else {
		setTimeout(nextNews,500);
	}
}

function changeNext() {

}

function changePrev() {
	curr_news++;

	if(curr_news > last_news) {
		curr_news = first_news;
	}

	curr_news++;

	if(curr_news > last_news) {
		curr_news = first_news;
	}
}

$(document).ready(function() {
    $('#news_images').cycle({
		fx: 'fade',
		timeout: 8000,
                prev:   '#prev_arrow',
                next:   '#next_arrow',
		before: onChangeNext
	});
});


displayNews();
</script>




<div id="accueil_news">
	<div id="news_images">
  <?php
    for($i = $last; $i >= $first; $i--) {
      echo '		<img src="res/news/'.$i.'.jpg" />';
    }
  ?>

	</div>

        <div id="news_arrows">
                <div id="prev_arrow_d"><a id="prev_arrow" onclick="changePrev();" href="#"><img src="res/left_arrow.png" onMouseUp="this.src='res/left_arrow.png'" onMouseDown="this.src='res/left_arrow_clicked.png'" /></a></div>
                <div id="next_arrow_d"><a id="next_arrow" onclick="changeNext();" href="#"><img src="res/right_arrow.png" onMouseUp="this.src='res/right_arrow.png'" onMouseDown="this.src='res/right_arrow_clicked.png'" /></a></div>
        </div>

	<div id="news_texts">
  <?php
    for($i = $first; $i <= $last; $i++) 
		{
      $query = 'SELECT * FROM News WHERE news_id='.$i;

      $db->ApplyQuery($query);

      $data = $db->GetNext();
      $title = $data['news_title'];
      $msg = $data['news_message'];
      $date = $data['news_date'];

      if(strlen($msg) > 700) {
        $msg = substr($msg, 0, 700);
      }

      echo '<div id="news_'.$i.'">';
      echo '<p class="news_title">'.$title.'</p>';
      echo '<p class="news_date">'.$date.'</p>';
      echo '<p class="news_text">'.$msg.'</p>';
      echo '</div>';
    }

    $db->Close();
  ?>
	</div>

	<a id="news_link" href="">Lire la suite...</a>
</div>

<br/><br/><br/>
<p class="text_paragraph">
Le Club de Tennis de Table de Rolle a &eacute;t&eacute; fond&eacute; en 1952 par sept Rollois, dont Jacques Magnin, Richard Muller, Gaston Bise et Serge Lecoultre. <br/>
D'apr&egrave;s nos archives, le CTT Rolle - qui comprenait &agrave; l'&eacute;poque moins d'une dizaine de membres - s'entra&icirc;ne depuis mars 1953 dans la salle communale de Rolle.<br/><br/>

Chaque club de TT d&eacute;pend d'une association faiti&egrave;re en fonction de sa situation g&eacute;ographique, en g&eacute;n&eacute;ral regroup&eacute;e par canton(s). Rolle d&eacute;pend de l'Association Vaud, Valais, Fribourg (AVVF).<br/>
En Suisse, il existe ainsi 8 associations qui d&eacute;pendent elles-m&ecirc;mes de la F&eacute;d&eacute;ration Suisse de Tennis de Table (FSTT). La Suisse ne compte pas moins de 200 clubs officiels et il en existe, &agrave; ce moment, environ 50 affili&eacute;s &agrave; l'AVVF.
</p>


